name: "The Luxe Studio"
tagline: "Timeless cuts & color with modern flair"
timezone: "America/New_York"
address: "145 Grove Street, Brooklyn, NY 11206"
phone: "+1-718-555-0199"
email: "appointments@theluxestudionyc.com"
website: "https://theluxestudionyc.com"

hours:
  monday: { open: "09:00", close: "19:00" }
  tuesday: { open: "09:00", close: "19:00" }
  wednesday: { open: "09:00", close: "19:00" }
  thursday: { open: "10:00", close: "20:00" }
  friday: { open: "10:00", close: "20:00" }
  saturday: { open: "09:00", close: "17:00" }
  sunday: { open: null, close: null }

services:
  - name: "Signature Cut & Style"
    duration_minutes: 60
    stylists: ["Kim Harper", "Alex Reed"]
    price: "$95"
    description: "Customized cut, wash, and blowout tailored to face shape and lifestyle."
  - name: "Color & Highlights"
    duration_minutes: 120
    stylists: ["Jordan Miles"]
    price: "$180"
    description: "Dimensional color with gloss finish and personalized toning."
  - name: "Express Blowout"
    duration_minutes: 45
    stylists: ["Alex Reed"]
    price: "$55"
    description: "Wash and blow dry for a polished, event-ready look."
  - name: "Keratin Smoothing"
    duration_minutes: 150
    stylists: ["Kim Harper"]
    price: "$250"
    description: "Frizz-fighting treatment for long-lasting shine and smoothness."
  - name: "Kids Cut"
    duration_minutes: 30
    stylists: ["Kim Harper"]
    price: "$40"
    description: "Friendly, patient styling for children ages 4-12."

policies:
  cancellation_notice_hours: 24
  late_arrival_grace_minutes: 10
  no_show_fee: "$40"
  payment_methods: ["Visa", "Mastercard", "AmEx", "Apple Pay"]

stylists:
  - name: "Kim Harper"
    specialties: ["Precision cuts", "Keratin treatments", "Kids styling"]
    bio: "15 years of experience transforming classic cuts with modern tailoring."
  - name: "Alex Reed"
    specialties: ["Blowouts", "Short cuts", "Texture-friendly styling"]
    bio: "Editorial stylist known for conversation-driven service and versatile looks."
  - name: "Jordan Miles"
    specialties: ["Balayage", "Color correction", "Lived-in blondes"]
    bio: "Color theory expert delivering high-impact transformations with healthy shine."

amenities:
  - "Complimentary espresso bar"
  - "WiFi lounge"
  - "Quiet treatment room with aromatherapy"

reminders:
  confirmation_window_hours: 12
  reminder_sms_hours_before: 24
  previsit_email_minutes_before: 60


